[CP-20164] Allow users to set secret filepath and filename for agent server container
Cloudzero/cloudzero-charts pull request #63
Opened 2024-07-18 01:47 UTC by dmepham

By submitting a PR to this repository, you agree to the terms within the [CloudZero Code of Conduct](https://github.com/cloudzero/template-cloudzero-open-source/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/cloudzero/template-cloudzero-open-source/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

users may want to manage secrets with Hashicrop Vault, which requires no k8s Secrets at all. instead, it injects secrets to the container filesystem based on an annotation. the filename and filepath that the secret is inject to is based on the annotation provided by the user. to allow users to use Vault, we need to allow arbitrary secret filepaths to be specified, and we need to allow users to deploy without any k8s secret at all

### References
Vault documentation: https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-sidecar

### Testing
testing is in progress

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `main`

2024-07-18 19:25 UTC, bdrennz approved these changes
Looks good!

2024-07-18 21:04 UTC, josephbarnett requested changes
I think we need a small change to the git workflow for installation test:
> https://github.com/Cloudzero/cloudzero-charts/actions/runs/9984162965/job/27592934253?pr=63#step:8:490

Otherwise this looks good

2024-07-18 22:01 UTC, dmepham commented on charts/cloudzero-agent/values.yaml
> +  containerSecretFileName: value
I originally named with `cz-api-key`, which I think is a better name than `value`. but I'm worried that users that have created secrets externally with the `value` name could see this fail on upgrade

2024-07-19 13:17 UTC, josephbarnett approved these changes
👍

2024-07-19 13:17 UTC, merged